#!/bin/sh
#set -x

#  Dazuko linux_dev_conf. Configure Dazuko for Linux 2.6 device API.
#  Written by John Ogness <dazukocode@ogness.net>
#
#  Copyright (c) 2004, 2005, 2006 H+BEDV Datentechnik GmbH
#  Copyright (c) 2006 Avira GmbH
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright notice,
#  this list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#
#  3. Neither the name of Dazuko nor the names of its contributors may be used
#  to endorse or promote products derived from this software without specific
#  prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.


usage_exit()
{
	echo "usage: $0 <device.h>"
	exit 1
}

if [ $# -ne 1 ]
then
	usage_exit
fi

if [ ! -f "$1" ]
then
	usage_exit
fi

FILE="dazuko_linux26_device_def.h"
TMPFILE="$FILE.tmp"
Z="[^),]*"

cat $1 | tr -d "\n" > $TMPFILE

echo "/* defines for device API identification */" > $FILE
echo "" >> $FILE

cat $TMPFILE | grep -q \
"class_device_create${Z}(${Z}struct${Z}class${Z}\*${Z},${Z}struct${Z}class_device${Z}\*${Z},${Z}dev_t${Z},${Z}struct${Z}device${Z}\*${Z},${Z}char${Z}\*${Z},${Z})"
if [ $? -eq 0 ]
then
	echo "#define CLASS_class_device_create_2_6_15" >> $FILE
else
	cat $TMPFILE | grep -q \
	"device_create${Z}(${Z}struct${Z}class${Z}\*${Z},${Z}struct${Z}device${Z}\*${Z},${Z}dev_t${Z},${Z}char${Z}\*${Z},${Z})"
	if [ $? -eq 0 ]
	then
		echo "#define CLASS_device_create_2_6_26" >> $FILE
	fi
fi

rm -f $TMPFILE

exit 0

